import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { Client, Employee, Service } from "@/types";
import { formatDate, formatDateTime } from "@/utils/format";

const COMPANY_NAME = "Minocha & Minocha";
const COMPANY_TAGLINE = "Chartered Accountants";

export function generateCompanyReport(
  company: Client,
  employees: Employee[],
  services: Service[],
  generatedBy: string,
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const now = new Date();

  doc.setFillColor(33, 37, 41);
  doc.rect(0, 0, pageWidth, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(COMPANY_NAME, 14, 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(COMPANY_TAGLINE, 14, 21);

  doc.setTextColor(33, 37, 41);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Work Completed Report", 14, 42);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Company Details", 14, 54);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const details = [
    `Company: ${company.name}`,
    `GST Number: ${company.gst_number || "—"}`,
    `Email: ${company.email || "—"}`,
    `Phone: ${company.phone || "—"}`,
  ];
  details.forEach((line, i) => doc.text(line, 14, 62 + i * 6));

  let cursorY = 92;

  const groups = [...employees]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((emp) => ({
      emp,
      empServices: services.filter((s) => s.client_contact_id === emp.id),
    }))
    .filter((g) => g.empServices.length > 0);

  groups.forEach(({ emp, empServices }) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    const label = emp.designation
      ? `Client Contact: ${emp.name} (${emp.designation})`
      : `Client Contact: ${emp.name}`;
    doc.text(label, 14, cursorY);

    autoTable(doc, {
      startY: cursorY + 4,
      head: [["Service", "Assigned Staff", "Status", "Due Date", "Completion Date"]],
      body: empServices.map((s) => [
        s.name,
        s.assigned_to || "—",
        s.status,
        formatDate(s.due_date),
        formatDate(s.completed_at),
      ]),
      headStyles: { fillColor: [33, 37, 41] },
      styles: { fontSize: 9, cellPadding: 3 },
      theme: "striped",
    });

    // @ts-expect-error lastAutoTable is added by the plugin
    cursorY = (doc.lastAutoTable?.finalY ?? cursorY) + 12;
  });

  const afterTableY = cursorY;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Summary", 14, afterTableY);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const completed = services.filter((s) => s.status === "Completed").length;
  doc.text(
    `${completed} of ${services.length} service(s) across ${groups.length} client contact(s) for ${company.name} are completed.`,
    14,
    afterTableY + 7,
    { maxWidth: pageWidth - 28 },
  );
  doc.text(`Generated Date: ${formatDateTime(now.toISOString())}`, 14, afterTableY + 17);
  doc.text(`Generated By: ${generatedBy}`, 14, afterTableY + 23);

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const h = doc.internal.pageSize.getHeight();
    doc.setDrawColor(220);
    doc.line(14, h - 16, pageWidth - 14, h - 16);
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(`${COMPANY_NAME} — Confidential`, 14, h - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, h - 10, { align: "right" });
  }

  doc.save(
    `Work-Completed-${company.name.replace(/\s+/g, "-")}-${now
      .toISOString()
      .slice(0, 10)}.pdf`,
  );
}

export function exportServicesCsv(
  rows: {
    company: string;
    contact: string;
    service: string;
    assignedTo: string;
    status: string;
    dueDate: string;
    recurring: boolean;
    recurrence?: string;
  }[],
) {
  const header = [
  "Company",
  "Client Contact",
  "Service",
  "Assigned Staff",
  "Status",
  "Due Date",
  "Recurring",
  "Recurrence",
];
  const escape = (v: string) => `"${(v ?? "").replace(/"/g, '""')}"`;
  const lines = [
    header.map(escape).join(","),
    ...rows.map((r) =>
      [
        r.company,
  r.contact,
  r.service,
  r.assignedTo,
  r.status,
  r.dueDate,
  r.recurring ? "Yes" : "No",
  r.recurrence ?? "",
      ]
        .map(escape)
        .join(","),
    ),
  ];
  const blob = new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `services-report-${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}
