import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { formatDateTime } from "@/utils/format";
import type { ReportRow } from "@/types/report";

const COMPANY_NAME = "Minocha & Minocha";
const COMPANY_TAGLINE = "Chartered Accountants";

export function generateReportPdf(
  title: string,
  rows: ReportRow[],
  generatedBy: string,
) {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const now = new Date();

  // ===============================
  // Header
  // ===============================

  doc.setFillColor(33, 37, 41);
  doc.rect(0, 0, pageWidth, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(COMPANY_NAME, 14, 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(COMPANY_TAGLINE, 14, 21);

  // ===============================
  // Report Title
  // ===============================

  doc.setTextColor(30);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text(title, 14, 42);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  doc.text(
    `Generated: ${formatDateTime(now.toISOString())}`,
    14,
    50,
  );

  doc.text(
    `Generated By: ${generatedBy}`,
    14,
    56,
  );

  doc.text(
    `Total Records: ${rows.length}`,
    pageWidth - 14,
    50,
    { align: "right" },
  );

  // ===============================
  // Table
  // ===============================

  autoTable(doc, {
    startY: 64,

    head: [[
      "Company",
      "Client",
      "Service",
      "Assigned",
      "Status",
      "Due Date",
      "Recurring",
      "Frequency",
    ]],

    body: rows.map((row) => [

      row.company,

      row.contact,

      row.service,

      row.assignedTo,

      row.status,

      row.dueDate,

      row.recurring ? "Yes" : "No",

      row.recurring
        ? row.recurrence ?? "-"
        : "-",

    ]),

    theme: "striped",

    headStyles: {

      fillColor: [33, 37, 41],

      textColor: [255, 255, 255],

      fontStyle: "bold",

      halign: "center",

    },

    styles: {

      fontSize: 9,

      cellPadding: 3,

      valign: "middle",

    },

    alternateRowStyles: {

      fillColor: [248, 249, 250],

    },

    columnStyles: {

      0: { cellWidth: 34 },

      1: { cellWidth: 30 },

      2: { cellWidth: 35 },

      3: { cellWidth: 30 },

      4: { cellWidth: 24 },

      5: { cellWidth: 24 },

      6: { cellWidth: 18 },

      7: { cellWidth: 22 },

    },

  });

  // ===============================
  // Footer
  // ===============================

  const pageCount = doc.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {

    doc.setPage(i);

    doc.setDrawColor(220);

    doc.line(
      14,
      pageHeight - 16,
      pageWidth - 14,
      pageHeight - 16,
    );

    doc.setFontSize(8);

    doc.setTextColor(120);

    doc.text(
      `${COMPANY_NAME} — Confidential`,
      14,
      pageHeight - 10,
    );

    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 14,
      pageHeight - 10,
      { align: "right" },
    );
  }

  // ===============================
  // Save
  // ===============================

  const filename =
    title
      .replace(/\s+/g, "-")
      .replace(/[^\w-]/g, "");

  doc.save(
    `${filename}-${now.toISOString().slice(0, 10)}.pdf`,
  );
}